---
title: "Thyroid Analysis dashboard"
author: "LAASSAIRI Abdellah"
date: "2022-12-17"
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(stringr)
library(ggplot2)
library(dplyr)
library(plotly)

```

```{r}
df=read.csv("data/thyroid.csv")
head(df)
```

```{r}
raw_data=read.csv("/home/odeck/Desktop/SDR/Project/data/thyroid.csv")
head(df)
```

```{r}
raw_data$ThryroidClass=factor(raw_data$ThryroidClas)
categorical_cols=c('patient_gender','presc_thyroxine','queried_why_on_thyroxine','presc_anthyroid_meds','sick','pregnant',
              'radioactive_iodine_therapyI131','query_hypothyroid','query_hyperthyroid','lithium','goitre','tumor',
              'hypopituitarism','psych_condition', 'thyrox_util_rate_T4U_measured','FTI_measured')

numerical_cols=c('patient_age','TSH_measured','TSH_reading','T3_measured','T3_reading','T4_measured','T4_reading',
                 'thyrox_util_rate_T4U_measured','thyrox_util_rate_T4U_reading','FTI_measured','FTI_reading')


raw_data$patient_age<-as.numeric(raw_data$patient_age)
raw_data[categorical_cols] <- lapply(raw_data[categorical_cols], factor)
print(a)

```

------------------------------------------------------------------------

Column {data-width=650}

### Chart A
